
name: Java CI with Maven

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      working-directory: ./Unsolo-rockets

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: favouritedan
        password: Oluchukwu74
      
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: Unsolo-rockets/Dockerfile
        context: .
        push: true
        tags: favouritedan/unsolo-rockets:latest

    # - name: Build & Push Docker Image
    #   uses: mr-smithers-excellent/docker-build-push@v5
    #   with:
    #     image: unsolo-travels
    #     tags: latest
    #     registry: docker.io
    #     dockerfile: Unsolo-rockets/Dockerfile
    #     username: favouritedan
    #     password: Oluchukwu74

#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#    - name: Update dependency graph
#      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
